repos:
  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: v0.2.1  # Use the ref you want to point at
    hooks:
      - id: clang-format
        args: [--style=Mozilla] # Other coding style: Google, LLVM, GNU, Chromium, Microsoft, Mozilla, WebKit.
